#########################################################################################################
# 001-HEADER
#########################################################################################################
# menu
menu:
    home: /
    archive: /archives
    categories: /categories
    tags: /tags
    about: /about
    gallery: /gallery

# favicon & logo
favicon: /img/favicon.ico
logo: /img/logo.png 

# background_image
# mask_alpha: 0 ~ 1
# mode: normal | random_you | random_other
# normal_url: /img/header-bg.jpg
# random_you_url: https://sariay.github.io/Random-img/
# random_other_url: https://source.unsplash.com/collection/954550/1920x1080 | https://api.berryapi.net/?service=App.Bing.Images&day=-0
mask_alpha: 0.4
background_image:
    mode: normal
    normal_url: https://picsum.photos/1920/1080
    random_you_max: 110 
    random_you_url: https://picsum.photos/1920/1080
    random_other_url: https://picsum.photos/1920/1080

# motto 
# source: local | hitokoto
motto:
	enable: true
	source: local
    
#########################################################################################################
# 002-PROLOADER
#########################################################################################################
# animation: spinner | transition | cyclic
preloader:
    enable: true
    animation: spinner

#########################################################################################################
# 003-INDEX
#########################################################################################################
# index-style: pure | cart
index_style: cart

# index_cart_cover
cover: https://s2.ax1x.com/2020/02/04/1BrA0O.jpg
lazy_image: https://s2.ax1x.com/2020/02/10/15r98s.gif

#########################################################################################################
# 004-POST
#########################################################################################################
# post_relate
relate:
    enable: true
    posts_limit: 10
    posts_excerpt: 60

# post_comment
comment:
    enable: true
    shortname: ailoveu.disqus.com
    count: true

gitalk:
    enable: false
    clientID: '333--' 
    clientSecret: '333--' 
    repo: annie-gitalk 
    owner: Sariay 
    admin: Sariay 
    distractionFreeMode: true
    #去除 more、index.html、?query=123等格式尾部 
    hrefTrimend: '#.*$,\\?.*$,index.html$' 
    
valine: 
    enable: true
    appid: '6EAKMFXHkl9DUQpOKtVtJMwJ-gzGzoHsz'
    appkey: 'fTeVCApFb2zauCWeBcDhyxdy'
    placeholder: 匿名发言
    
livere: 
    enable: false
    livere_uid: 'sdd'
    
# post_count
leancloud_count:
    enable: true
    appid: '6EAKMFXHkl9DUQpOKtVtJMwJ-gzGzoHsz'
    appkey: 'fTeVCApFb2zauCWeBcDhyxdy'
    serverURLs: 'https://6eakmfxh.lc-cn-n1-shared.com'
    like_post:
        enable: true
    visit_post:
        enable: true
    topN_post: 
        enable: true 
        limit: 10

busuanzi_count:
    enable: false

baidu_analytics:
    enable: true
    id: edd020d1de1a782924823ea413e64fc5

cnzz_analytics:
    enable: false
    id:

google_analytics:
    enable: false
    id:

tencent_analytics:
    enable: false
    id:

# post_toc
post_toc:
    enable: true
    katelog: true

feed:
    type: atom
    path: atom.xml
    limit: 20
# post_mathJax
mathjax:
  enable: true
  
# post_code
# highlight_theme: normal | night | night blue | night bright | night eighties
highlight_theme: normal
code_copy:
    enable: true

# post_excerpt for index page
excerpt_cart: 80
excerpt_pure: 300   
excerpt_link: true

# post_share
share:
    enable: true
# https://www.addthis.com/
# 注意浏览器的内容拦截插件
addThis:
    enable: false
    id: ra-xxx
# http://share.baidu.com/code
baiduShare: 
    enable: false
    style: button # you can add slide style!
# https://www.sharethis.com/onboarding-cms/    
shareThis:
    enable: false
    id: 5c-xxx
# https://github.com/overtrue/share.js
socialShare:
    enable: true

#########################################################################################################
# 005-FOOTER
#########################################################################################################
# social links
# Check the icon in the page of Icomoon
social:
	zhihu: 
        url: https://www.zhihu.com/people/AILOVEUU
        icon: <span class="icon-zhihu"></span>
	github:
        url: https://github.com/AILOVEU
        icon: <span class="icon-github"></span>
	weibo: 
        url: https://www.weibo.com/p/1005055306271796
        icon: <span class="icon-sina-weibo "></span>  
	douban:
        url: https://www.douban.com/people/AILOVEUU
        icon: <span class="icon-douban "></span>  
# copyright  
since: 2019
author: AILOVEU

#########################################################################################################
# 006-GALLERY PAGE
#########################################################################################################
# gallery page
# gallery_format: natural | square
gallery_format: natural
# one time to load 4 rows or other count, 0 to load img automatically when scrolling.(0,1,2,3,4,5,6......)
gallery_limit: 0
# data url
gallery_data: plugin/gallerypage/data.json

#########################################################################################################
# 007-LOCAL SEARCH
#########################################################################################################
# Local search
# Dependencies: https://github.com/flashlab/hexo-generator-search
local_search:
    enable: true
    # if auto, trigger search by changing input
    # if manual, trigger search by pressing enter key or search button
    trigger: auto
    # show top n results per article, show all results by setting to -1
    top_n_per_article: 2

#########################################################################################################
# 008-OTHERS
#########################################################################################################
# when click, emerge heart
love:
    enable: true

# back to top
totop:
    enable: true

# mermaid chart
mermaid: ## mermaid url https://github.com/knsv/mermaid
  enable: true  # default true
  version: "7.1.2" # default v7.1.2
  options:  # find more api options from https://github.com/knsv/mermaid/blob/master/src/mermaidAPI.js
    #startOnload: true  // default true
highlight:
  enable: false
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: false
  hljs: false